### ISSUE TITLE
Use poetry-core as build-backend

### ISSUE THREAD

**Issue by FRidh** [srstevenson/xdg#43]
The build backend of `poetry` was split into a separate package called `poetry-core`.

Please update your `pyproject.toml` to use
```toml
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

For more info, see https://github.com/python-poetry/poetry-core#poetry-core.
